### ISSUE TITLE
Mobile menu doesn't expand collapse on clicking

### ISSUE THREAD

**Issue by 10kresources** [bakateam/merakiui#50]
I copied the code from Headers > Ecommerce one and pasted in CodePen. Added a reference to TailwindCSS, but when I resize the window to see the menu menu, the mobile menu is expanded by default and doesn't collapse/expand on clicking. Do I need some additional JS to make that work? If so, can that be included in the code available?

**Comment by khatabwedaa** [comment]
Yup read the comment on the component code, if you use Vue js you can just copy the code from [here](https://github.com/bakateam/merakiui/blob/main/components/ui/Navbars/ECommerce.vue)
